CC_TEXTURES_DIR: '/home/bproc/input/cc_textures'
OUTPUT_DIR: '/home/bproc/output'
ENABLE_DEPTH: true
DEPTH_SCALE: 0.00005
NUM_SCENES: 1
NUM_CAMERAS_PER_SCENE: 1

OBJECT:
    FILE: "/home/bproc/input/obj_000007.ply"
    # m / mm / auto
    UNIT: 'auto'
    DECIMATION: 15000  # -1 for no decimation
    MOVE_TO_MASS_CENTER: true
    # auto / smooth / flat
    SHADING_MODE: 'auto'
    POSE_SAMPLER:
        MIN_NUM: 10
        MAX_NUM: 100
        MIN_HEIGHT: 1
        MAX_HEIGHT: 1.5
        ENABLE_PHYSICS: true
        PHYSICS:
            MIN_SIMULATION_TIME: 3
            MAX_SIMULATION_TIME: 10
            SUBSTEPS_PER_FRAME: 15
            SOLVER_ITERS: 15
    MATERIAL_SAMPLER:
        MIN_GRAY: 0.0
        MAX_GRAY: 1.0
        MIN_ROUGHNESS: 0
        MAX_ROUGHNESS: 0.5
        MIN_SPECULAR: 0.3
        MAX_SPECULAR: 1.0
        MIN_METALLIC: 0
        MAX_METALLIC: 1.0

TOTE:
    # auto / scalar
    WIDTH: 0.265
    LENGTH: 0.355
    HEIGHT: 0.15
    WALL_VISIBLE: true
    RANDOM_TEXTURE: true

CAMERA:
    INTRINSICS:
        FX: 2400
        FY: 2400
        PPX: 993
        PPY: 758
        WIDTH: 2048
        HEIGHT: 1536
        RANDOM_PERCENT: 5
    POSE_SAMPLER:
        MIN_HEIGHT: 1.2
        MAX_HEIGHT: 1.8
        MIN_ELEVATION: 75
        MAX_ELEVATION: 90

LIGHT:
    MIN_NUM: 1
    MAX_NUM: 3
    MIN_ENERGY: 1
    MAX_ENERGY: 20
    MIN_HEIGHT: 1.2
    MAX_HEIGHT: 1.8
    MIN_ELEVATION: 75
    MAX_ELEVATION: 90
